#:schema node_modules/wrangler/config-schema.json
name = "nautilus"
compatibility_date = "2026-01-18"

[assets]
# Keep the directory, but REMOVE the binding line
directory = "./public"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"

[vars]
HUGO_VERSION = "0.154.5"

[build]
command = "chmod +x build.sh && ./build.sh"
