#:schema node_modules/wrangler/config-schema.json
name = "nautilus"
compatibility_date = "2026-01-18"
directory = "./public"
not_found_handlin = "404-page"

[vars]
HUGO_VERSION = "0.154.5"

[build]
command = "./build.sh"


